[alias]
today = "run --quiet --release --features today -- today"
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --release -- time"

[env]
AOC_YEAR = "2025"

# in .bashrc (because  Z3_SYS_Z3_HEADER needs a win path, not a msys one)
#export Z3_LIBRARY_PATH_OVERRIDE=
#export Z3_SYS_Z3_HEADER=

